<?php
/**
* @file
* Saves content as a .tex file and then processes it using XeLaTeX.
*/

/**
 * Implements hook_file_download().
 *
 * A private file can be downloaded only if at least one module specifies some
 * headers and no module revokes permission by returning -1.
 */
function xelatex_file_download($uri) {
  global $user;
  $filename = $user->uid . '-transcript';
  $pdf_file = $filename . '.pdf';
  $directory = 'private://transcripts/';
  $pattern = '#' . $directory . $pdf_file . '#';
  if (preg_match($pattern, $uri) && is_readable($uri)) {
    return array('Content-Type' => 'application/pdf');
  }
}