<?php
/**
 * @file
 * Code for the Recurring Dates Exclusion Sets feature.
 */

include_once 'recurring_dates_exclusion_sets.features.inc';

/**
 * Implements hook_node_form_FORM_ID_alter().
 */
function recurring_dates_exclusion_sets_form_event_node_form_alter(&$form, &$form_state, $form_id) {
  $form['exclude_date_sets'] = array(
    '#type' => 'checkbox',
    '#title' => t("Exclude Date Sets"),
    '#required' => FALSE,
  );


//$exceptions = $form['#node']->field_date_of_event[LANGUAGE_NONE][0]['rrule'];
//$exceptions = $form['#node']->field_date_of_event[LANGUAGE_NONE][0]['rrule']['show_exceptions'];
//['field_test[und][0][rrule][show_exceptions]']
//return print_r($exceptions);
//  $form['#node']->['field_date_of_event'][LANGUAGE_NONE][0]['rrule']['show_exceptions'] = array(
//    '#title' => t("Exclude specific dates"),
//  );
//    return print_r($form);
}


function recurring_dates_exclusion_sets_form_alter(&$form, &$form_state, $form_id) {
  drupal_set_message($form_id);
}

/**
 * Implements hook_field_widget_form_alter.
 */

function recurring_dates_exclusion_sets_field_widget_form_alter(&$element, &$form_state, $context) {

  $field = $context['field'];

  if (in_array($field['type'], array('date', 'datetime', 'datestamp'))) {
    if (!empty($field['settings']['repeat'])) {
      $element['show_repeat_settings']['#title'] = 'Repeat 6th HELLO';
    }
  }
}
